name: planCEvent
version: '1.0-SNAPSHOT'
main: de.illy.planCEvent.PlanCEvent
api-version: '1.21'


commands:
  event:
    description: event mechanic
  dungeon:
    description: start a dungeon
  hub:
    description: teleport to the hub
  giveitems:
    description: give items
  toggledamage:
    description: toggle damage calc
  spawnmob:
    description: spawn a custom mob
  opencase:
    description: open a case
